name: Reusable Rust Job

on:
  workflow_call:
    inputs:
      commands:
        required: true
        type: string
      install_binstall:
        required: false
        type: boolean
        default: false
      binstall_crates:
        required: false
        type: string
        default: ""
      rust_toolchain:
        required: false
        type: string
        default: stable

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: ${{ inputs.rust_toolchain }}
          components: rustfmt, clippy

      - name: Cache cargo artifacts
        uses: Swatinem/rust-cache@v2

      - name: Install cargo-binstall
        if: ${{ inputs.install_binstall }}
        uses: cargo-bins/cargo-binstall@main

      - name: Install required cargo binaries
        if: ${{ inputs.install_binstall && inputs.binstall_crates != '' }}
        shell: bash
        run: |
          set -euo pipefail
          cargo binstall --no-confirm ${{ inputs.binstall_crates }}

      - name: Run commands
        shell: bash
        run: |
          set -euo pipefail
          ${{ inputs.commands }}
