name: Nightly

on:
  schedule:
    - cron: '0 2 * * *'
  workflow_dispatch:

concurrency:
  group: nightly-${{ github.ref }}
  cancel-in-progress: false

jobs:
  coverage:
    uses: ./.github/workflows/_reusable_rust.yml
    with:
      commands: |
        bash ci/nightly_coverage.sh

  performance:
    uses: ./.github/workflows/_reusable_rust.yml
    with:
      commands: |
        bash ci/nightly_perf.sh

  e2e:
    uses: ./.github/workflows/_reusable_rust.yml
    with:
      commands: |
        bash ci/nightly_e2e.sh
